
from Lib.___Local___ import *
def DATA_intents(text):
    Game_List = ['هستی']
    

    politicsURL = {
        'farsnews': 'https://www.farsnews.com/rss/politics',
        'isna': 'https://www.isna.ir/rss/tp/14',
        'tasnimnews': 'https://www.tasnimnews.com/fa/rss/feed/0/7/1/%D8%B3%DB%8C%D8%A7%D8%B3%DB%8C',
        'yjc': 'https://www.yjc.ir/fa/rss/3',
        'mehrnews': 'https://www.mehrnews.com/rss/tp/7',
        'tabnak': 'https://www.tabnak.ir/fa/rss/1/2',
        'irna': 'https://www.irna.ir/rss/tp/5',
        'econews': 'http://econews.ir/fa/news/feed/764',
        'khabaronline': 'https://www.khabaronline.ir/rss/tp/1',
        'asriran': 'https://www.asriran.com/fa/rss/1/1',
        'mashreghnews': 'https://www.mashreghnews.ir/rss/tp/2',
        'entekhab': 'https://www.entekhab.ir/fa/rss/2',
        'jahannews': 'http://www.jahannews.com/rssci.uy2-s2tuu-5b1,ydk.8al2as.2.xml',
        'alef': 'https://www.alef.ir/rss/latest/politics.xml',
        'ana': 'http://ana.ir/fa/rss/service/12',
        'imna': 'https://www.imna.ir/rss/tp/28',
        'aryanews': 'http://www.aryanews.com/Feed.aspx?svc=1&l=fa-ir',
        'iqna': 'http://iqna.ir/en/rss/3/mostvisited',
        'iribnews': 'http://www.iribnews.ir/fa/rss/5'
    }
    # 2
    economyURL = {
        'farsnews': 'https://www.farsnews.com/rss/economy',
        'isna': 'https://www.isna.ir/rss/tp/34',
        'tasnimnews': 'https://www.tasnimnews.com/fa/rss/feed/0/7/7/%D8%A7%D9%82%D8%AA%D8%B5%D8%A7%D8%AF%DB%8C',
        'yjc': 'https://www.yjc.ir/fa/rss/6',
        'mehrnews': 'https://www.mehrnews.com/rss/tp/25',
        'tabnak': 'https://www.tabnak.ir/fa/rss/6',
        'irna': 'https://www.irna.ir/rss/tp/20',
        'econews': 'http://econews.ir/fa/news/feed/991',
        'khabaronline': 'https://www.khabaronline.ir/rss/tp/2',
        'asriran': 'https://www.asriran.com/fa/rss/1/4',
        'mashreghnews': 'https://www.mashreghnews.ir/rss/tp/16',
        'entekhab': 'https://www.entekhab.ir/fa/rss/5',
        'jahannews': 'http://www.jahannews.com/rssew.skj1zjyss1rhx2k4m.ib9jbx.j.xml',
        'alef': 'https://www.alef.ir/rss/latest/economy.xml',
        'ana': 'http://ana.ir/fa/rss/service/22',
        'imna': 'https://www.imna.ir/rss/tp/5',
        'aryanews': 'http://www.aryanews.com/Feed.aspx?svc=4&l=fa-ir',
        'iribnews': 'http://www.iribnews.ir/fa/rss/6'
    }
    # 3
    worldURL = {
        'farsnews': 'https://www.farsnews.com/rss/world',
        'isna': 'https://www.isna.ir/rss/tp/17',
        'tasnimnews': 'https://www.tasnimnews.com/fa/rss/feed/0/7/8/%D8%A8%DB%8C%D9%86-%D8%A7%D9%84%D9%85%D9%84%D9%84',
        'yjc': 'https://www.yjc.ir/fa/rss/9',
        'mehrnews': 'https://www.mehrnews.com/rss/tp/8',
        'tabnak': 'https://www.tabnak.ir/fa/rss/17',
        'irna': 'https://www.irna.ir/rss/tp/1',
        'econews': 'http://econews.ir/fa/news/feed/784',
        'khabaronline': 'https://www.khabaronline.ir/rss/tp/5',
        'asriran': 'https://asriran.com/fa/rss/1 /3',
        'mashreghnews': 'https://www.mashreghnews.ir/rss/tp/5',
        'entekhab': 'https://www.entekhab.ir/fa/rss/3',
        'jahannews': 'http://www.jahannews.com/rssir.,ltizt4,,ik1pxlne.2cbtcy.t.xml',
        'alef': 'https://www.alef.ir/rss/latest/world.xml',
        'ana': 'http://ana.ir/fa/rss/service/20',
        'aryanews': 'http://www.aryanews.com/Feed.aspx?svc=3&l=fa-ir',
        'iqna': 'http://iqna.ir/en/rss/services/7',
        'iribnews': 'http://www.iribnews.ir/fa/rss/5'
    }
    # 4
    socialURL = {
        'farsnews': 'https://www.farsnews.com/rss/social',
        'isna': 'https://www.isna.ir/rss/tp/9',
        'tasnimnews': 'https://www.tasnimnews.com/fa/rss/feed/0/7/2/%D8%A7%D8%AC%D8%AA%D9%85%D8%A7%D8%B9%DB%8C',
        'yjc': 'https://www.yjc.ir/fa/rss/5',
        'mehrnews': 'https://www.mehrnews.com/rss/tp/6',
        'tabnak': 'https://www.tabnak.ir/fa/rss/3',
        'irna': 'https://www.irna.ir/rss/tp/32',
        'econews': 'http://econews.ir/fa/news/feed/767',
        'khabaronline': 'https://www.khabaronline.ir/rss/tp/4',
        'asriran': 'https://www.asriran.com/fa/rss/1/5',
        'mashreghnews': 'https://www.mashreghnews.ir/rss/tp/14',
        'entekhab': 'https://www.entekhab.ir/fa/rss/4',
        'jahannews': 'http://www.jahannews.com/rssf0.47wrywq44r,6mp73f.aigwij.w.xml',
        'alef': 'https://www.alef.ir/rss/latest/social.xml',
        'ana': 'http://ana.ir/fa/rss/service/21',
        'imna': 'https://www.imna.ir/rss/tp/3',
        'aryanews': 'http://www.aryanews.com/Feed.aspx?svc=5&l=fa-ir',
        'iqna': 'http://iqna.ir/en/rss/services/5',
        'iribnews': 'http://www.iribnews.ir/fa/rss/7',
    }
    # 5
    sportsURL = {
        'farsnews': 'https://www.farsnews.com/rss/sports',
        'isna': 'https://www.isna.ir/rss/tp/24',
        'tasnimnews': 'https://www.tasnimnews.com/fa/rss/feed/0/7/3/%D9%88%D8%B1%D8%B2%D8%B4%DB%8C',
        'yjc': 'https://www.yjc.ir/fa/rss/8',
        'mehrnews': 'https://www.mehrnews.com/rss/tp/9',
        'tabnak': 'https://www.tabnak.ir/fa/rss/2',
        'irna': 'https://www.irna.ir/rss/tp/14',
        'econews': 'http://econews.ir/fa/news/feed/766',
        'khabaronline': 'https://www.khabaronline.ir/rss/tp/6',
        'asriran': 'https://www.asriran.com/fa/rss/1/6',
        'mashreghnews': 'https://www.mashreghnews.ir/rss/tp/10',
        'entekhab': 'https://www.entekhab.ir/fa/rss/9',
        'jahannews': 'http://www.jahannews.com/rssdx.gmyefy,ggeltshmci.62ay2x.y.xml',
        'alef': 'https://www.alef.ir/rss/latest/sports.xml',
        'ana': 'http://ana.ir/fa/rss/service/24',
        'imna': 'https://www.imna.ir/rss/tp/7',
        'aryanews': 'http://www.aryanews.com/Feed.aspx?svc=6&l=fa-ir',
        'iqna': 'http://www.iribnews.ir/fa/rss/4',
        'iribnews': 'http://www.iribnews.ir/fa/rss/4'
    }
    # 6
    scienceURL = {
        'farsnews': 'https://www.farsnews.com/rss/scientific-academic',
        'isna': 'https://www.isna.ir/rss/tp/5',
        'yjc': 'https://www.yjc.ir/fa/rss/7',
        'mehrnews': 'https://www.mehrnews.com/rss/tp/5',
        'tabnak': 'https://www.tabnak.ir/fa/rss/1/72',
        'irna': 'https://www.irna.ir/rss/tp/180',
        'econews': 'http://econews.ir/fa/news/feed/768',
        'khabaronline': 'https://www.khabaronline.ir/rss/tp/7',
        'asriran': 'https://www.asriran.com/fa/rss/1/7',
        'mashreghnews': 'https://www.mashreghnews.ir/rss?pl=19',
        'entekhab': 'https://www.entekhab.ir/fa/rss/8',
        'alef': 'https://www.alef.ir/rss/latest/technology.xml',
        'imna': 'https://www.imna.ir/rss/tp/6',
        'aryanews': 'http://www.aryanews.com/Feed.aspx?svc=8&l=fa-ir',
        'iribnews': 'http://www.iribnews.ir/fa/rss/8/19',
    }
    # 7
    cultureURL = {
        'farsnews': 'https://www.farsnews.com/rss/culture',
        'isna': 'https://www.isna.ir/rss/tp/20',
        'tasnimnews': 'https://www.tasnimnews.com/fa/rss/feed/0/7/4/%D9%81%D8%B1%D9%87%D9%86%DA%AF%DB%8C',
        'yjc': 'https://www.yjc.ir/fa/rss/4',
        'mehrnews': 'https://www.mehrnews.com/rss/tp/2',
        'tabnak': 'https://www.tabnak.ir/fa/rss/21',
        'irna': 'https://www.irna.ir/rss/tp/41',
        'econews': 'http://econews.ir/fa/news/feed/765',
        'khabaronline': 'https://www.khabaronline.ir/rss/tp/3',
        'asriran': 'https://www.asriran.com/fa/rss/1/8',
        'mashreghnews': 'https://www.mashreghnews.ir/rss/tp/4',
        'entekhab': 'https://www.entekhab.ir/fa/rss/18',
        'jahannews': 'http://www.jahannews.com/rssgx.dja5qa6dd51kwvjoe.4rparn.a.xml',
        'alef': 'https://www.alef.ir/rss/latest/culture.xml',
        'ana': 'http://ana.ir/fa/rss/service/23',
        'imna': 'https://www.imna.ir/rss/tp/4',
        'aryanews': 'http://www.aryanews.com/Feed.aspx?svc=7&l=fa-ir',
        'iqna': 'http://iqna.ir/en/rss/services/6',
        'iribnews': 'http://www.iribnews.ir/fa/rss/8/28'
    }

    
    
    return {"DATA_intents": [
        
        {"Tag": "Greet",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['چطوره', 'احوالت', 'حالت', 'چطوری', 'خوبی'],
        "SecoundLayerKeywords": [],
        "Answers": ["عالی (◕‿◕✿)","خوبم (◕‿◕✿)","بهتر از این نمیشه (◕‿◕✿)","معلومه که خوبم (◕‿◕✿)"],
        "Actions": [],
        "Extra": [random.choice(['static//Media/Gif/gif_3.gif','static//Media/Gif/gif_20.gif','static//Media/Gif/gif_3.gif','static//Media/Gif/gif_4.gif'])],
        },

        {"Tag": "Greet",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['اسمت'],
        "SecoundLayerKeywords": ['چی','چه'],
        "Answers": [': ) من مددبات هستم'],
        "Actions": [],
        },
    
        {"Tag": "Greet",
        "MustBeKeywords": [['تو','هستی'],'کی'],
        "FirstLayerKeywords": ['کی','هستی','تو'],
        "SecoundLayerKeywords": [],
        "Answers": [' من اکبر هستم.  یک ربات با هوشِ مصنوعیِ قوی و آماده خدمتِ به شما'],
        "Actions": [],
        },

        {"Tag": "Greet",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['چی کار', 'چیکار','چه کار'],
        "SecoundLayerKeywords": ['میکنی','میدی'],
        "Answers": ['ʘ‿ʘ من هر کاری که نیاز داشته باشی رو میتونم انجام بدم '],
        "Actions": ['static//Media/Gif/gif_5.gif'],
        },

        {"Tag": "Greet",
        "MustBeKeywords": ['ساخت',['کی','چه کس','تو']],
        "FirstLayerKeywords": ['کی','چه','ساخت'],
        "SecoundLayerKeywords": ['توسط','تو'],
        "Answers": ['(◕‿◕✿) آقایان علیرضا شعبانی و پارسا سلیمانی'],
        "Actions": [],
        },

        {"Tag": "Greet",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['هلو','های','Hi','Hello','Hi','hi','Slm','slm','درود بر شما', 'درود', 'سلام', 'سلامٌ عَلِیکُم', 'درود فراوان', 'سلام بر تو باد', 'درودِ فراوان', 'سلام'],
        "SecoundLayerKeywords": [],
        "Answers": ['♥‿♥ درود بر شما ♥‿♥', 'درود ♥‿♥', 'سلام ♥‿♥', 'سلامٌ عَلِیکُم ♥‿♥', 'سلام بر تو باد ♥‿♥', 'درودِ فراوان'],
        "Actions": [],
        },

        {"Tag": "Play",
         'Web' : 'No',
        "MustBeKeywords": [['قران','قرآن']],
        "FirstLayerKeywords": ['قران','قرآن','پخش','قرايت','قرائت'],
        "SecoundLayerKeywords": ["سوره"],
        "Answers": [],
        "Actions": [[Audio().MusicPlay,(random.choice(["Sooreh_1"])),text]],
        },
    
        {"Tag": "Play",
         'Web' : 'No',
        "MustBeKeywords": [['اذان', 'ازان']],
        "FirstLayerKeywords": ['اذان', 'ازان'],
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Answers": [],
        "Actions": [[Audio().MusicPlay,((random.choice(["Azan"])),text)]],
        },

        {"Tag": "Play",
         'Web' : 'No',
        "MustBeKeywords": [['موزیک','آهنگ','اهنگ']],
        "FirstLayerKeywords": ['بهنام', 'بانی','موزیک', 'آهنگ', 'اهنگ'],
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Answers": [],
        "Actions": [[Audio().MusicPlay,random.choice(Audio().MusicNames("‌BehnamBani",1)),text]],
        },

        {"Tag": "Play",
         'Web' : 'No',
        "MustBeKeywords": [['موزیک','آهنگ','اهنگ']],
        "FirstLayerKeywords": ['حامد', 'بهرام','موزیک', 'آهنگ', 'اهنگ'],
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Answers": [],
        "Actions": [[Audio().MusicPlay,random.choice(Audio().MusicNames("HamedBahram",1)),text]],
        },

        {"Tag": "Play",
         'Web' : 'No',
        "MustBeKeywords": [['موزیک','آهنگ','اهنگ']],
        "FirstLayerKeywords": ['آرون', 'افشار','موزیک', 'آهنگ', 'اهنگ'],
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Answers": [],
        "Actions": [[Audio().MusicPlay,random.choice(Audio().MusicNames("AronAfshar",1)),text]],
        },

        {"Tag": "Play",
         'Web' : 'No',
        "MustBeKeywords": [['موزیک','آهنگ','اهنگ']],
        "FirstLayerKeywords": ['ترکیه', 'ترکیه','موزیک', 'آهنگ', 'اهنگ'],
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Answers": [],
        "Actions": [[Audio().MusicPlay,random.choice(Audio().MusicNames("Turkish",1)),text]],
        },

        {"Tag": "Play",
         'Web' : 'No',
        "MustBeKeywords": [['موزیک','آهنگ','اهنگ']],
        "FirstLayerKeywords": ['گیتار', 'جیپسی', 'فلامینگو','موزیک', 'آهنگ', 'اهنگ'],
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Answers": [],
        "Actions": [[Audio().MusicPlay,random.choice(Audio().MusicNames("Gypsy",1)),text]],
        },
        {"Tag": "Play",
         'Web' : 'No',
        "MustBeKeywords": [['موزیک','آهنگ','اهنگ']],
        "FirstLayerKeywords": ['جهان بخش', 'جهانبخش', 'بابک','موزیک', 'آهنگ', 'اهنگ'],
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Answers": [],
        "Actions": [[Audio().MusicPlay,random.choice(Audio().MusicNames("BabakJahanbakhsh",1)),text]],
        },
        
        {"Tag": "Play",
        "MustBeKeywords": [['موزیک','آهنگ','اهنگ','موسیقی']],
        "FirstLayerKeywords": ['موزیک','آهنگ','اهنگ','رندوم','تصادف'],
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Answers": [],
        "Actions": [[Audio().Music]],
        },
        
        
        {"Tag": "Play",
        "MustBeKeywords": [['صدا']],
        "FirstLayerKeywords": ['موزیک','آهنگ','اهنگ','رندوم','تصادف','طبیعت','دربا','اب','آب','باران','بارون','آب شار','اب شار','اقیانوس','باد'],
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Answers": [],
        "Actions": [[Audio().NatureMusic]],
        },
        
        {"Tag": "Play",
        "MustBeKeywords": [['ویدیو','فیلم','کلیپ']],
        "FirstLayerKeywords": ['ویدیو','فیلم','کلیپ','Ted','ted','علمی','باحال','جذاب','دانش'],
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Answers": [],
        "Actions": [[Audio().Video]],
        },
        
        {"Tag": "Play",
        "MustBeKeywords": [['Podcast','podcast','پادکست']],
        "FirstLayerKeywords": ['Podcast','podcast','آموزشی','انگیزشی','پادکست','اموزشی'],
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Answers": [],
        "Actions": [[Audio().Podcast]],
        },
        
        {"Tag": "Play",
        "MustBeKeywords": [['','موزیک','آهنگ','اهنگ','موسیقی','بدون خواننده','اینسترومنتال','بی خواننده','بی کلام']],
        "FirstLayerKeywords": ['بیکلام','بدون خواننده','اینسترومنتال','موزیک','آهنگ','اهنگ','بی خواننده','بی کلام'],
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Answers": [],
        "Actions": [[Audio().InstrumentalMusic]],
        },

        {"Tag": "Greet",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['پسری', 'پسر هستی', 'دختری', 'دختر هستی', 'جنسیت'],
        "SecoundLayerKeywords": ['تو'],
        "Answers": ['¯\_(ツ)_/¯ من یک ربات هستم و اسمم هم نمیدونم پسرونه است یا دخترونه!!!'],
        "Actions": [],
        },

        {"Tag": "Greet",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['چند سال', 'به دنیا', 'سن'],
        "SecoundLayerKeywords": ["تو"],
        "Answers": ['¯\_(ツ)_/¯ من کمتر از یک سال دارم'],
        "Actions": [],
        },

        {"Tag": "Greet",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['عالی','احسنت','عاشقتم','افرین','آفرین','عزیزی','عشقم', 'عزیزم', 'ازت خوشم میاد', 'عاشقتم', 'دوستت دارم', 'تورو دوست دارم', 'شمارو دوست دارم','تو رو دوست دارم','شما رو دوست دارم'],
        "SecoundLayerKeywords": [],
        "Answers": ['من هم شما رو دوست دارم'],
        "Actions": ['static//Media/Gif/gif_14.gif'],
        },

        {"Tag": "Greet",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['چه کاری علاقه داری', 'چه کاری لذت میبری', 'چه کاری خوشت میاد', 'چه کاری رو دوست داری', 'چه کاری را دوست داری', 'چه کاری دوست داری'],
        "SecoundLayerKeywords": [],
        "Answers": ['(¬‿¬) من عاشقِ باطری هستم و همیشه دوست دارم باطری اِستِعمال کنم'],
        "Actions": ['static//Media/Gif/gif_17.gif'],
        },

        {"Tag": "Greet",
        "MustBeKeywords": ['رنگ'],
        "FirstLayerKeywords": ['دوست داری','مورد علاقت','چیه'],
        "SecoundLayerKeywords": ['تو'],
        "Answers": ['من عاشق رنگِ سفید هستم'],
        "Actions": [],
        },

        {"Tag": "Date",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['چند شنبه','چه روزی'],
        "SecoundLayerKeywords": [],
        "Answers": [],
        "Actions": [[DateAndWeather().Day]],
        },

        {"Tag": "Date",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['چندم', 'تاریخ'],
        "SecoundLayerKeywords": [],
        "Answers": [],
        "Actions": [[DateAndWeather().Date]],
        },

        {"Tag": "Date",
         'Web' : 'No',
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['ساعت','چند'],
        "SecoundLayerKeywords": [],
        "Answers": ['خودت فکر کنی میفهمی : )'],
        "Actions": [],
        #[DateAndWeather().Time_Now]
        },

        {"Tag": "News",
        "MustBeKeywords": [['اخبار','خبر']],
        "FirstLayerKeywords": ['هنر','فرهنگ','اخبار'],
        "SecoundLayerKeywords": ['بخون','بخوان','بگو'],
        "Answers": [],
        "Actions": [[Others().News,cultureURL]],
        },

        {"Tag": "News",
        "MustBeKeywords": [['اخبار','خبر']],
        "FirstLayerKeywords": ['دانش','علم','اخبار'],
        "SecoundLayerKeywords": ['بخون','بخوان','بگو'],
        "Answers": [],
        "Actions": [[Others().News,scienceURL]],
        },

        {"Tag": "News",
        "MustBeKeywords": [['اخبار','خبر']],
        "FirstLayerKeywords": ['ورزش','اخبار'],
        "SecoundLayerKeywords": ['بخون','بخوان','بگو'],
        "Answers": [],
        "Actions": [[Others().News,sportsURL]],
        },

        {"Tag": "News",
        "MustBeKeywords": [['اخبار','خبر']],
        "FirstLayerKeywords": ['اجتماع','اخبار'],
        "SecoundLayerKeywords": ['بخون','بخوان','بگو'],
        "Answers": ['خبر اجتماع', 'اخبار اجتماع'],
        "Actions": [[Others().News,socialURL]],
        },

        {"Tag": "News",
        "MustBeKeywords": [['اخبار','خبر']],
        "FirstLayerKeywords": ['جهان','اخبار'],
        "SecoundLayerKeywords": ['بخون','بخوان','بگو'],
        "Answers": [],
        "Actions": [[Others().News,worldURL]],
        },

        {"Tag": "News",
        "MustBeKeywords": [['اخبار','خبر']],
        "FirstLayerKeywords": [ 'اقتصاد','اخبار'],
        "SecoundLayerKeywords": ['بخون','بخوان','بگو'],
        "Answers": [],
        "Actions": [[Others().News,economyURL]],
        },

        {"Tag": "News",
        "MustBeKeywords": [['اخبار','خبر']],
        "FirstLayerKeywords": ['سیاس','اخبار'],
        "SecoundLayerKeywords": ['بخون','بخوان','بگو'],
        "Answers": [],
        "Actions": [[Others().News,politicsURL]],
        },

        {"Tag": "News",
        "MustBeKeywords": [['اخبار','خبر']],
        "FirstLayerKeywords": ['اخبار'],
        "SecoundLayerKeywords": ['بخون','بخوان','بگو'],
        "Answers": [],
        "Actions": [[Others().News,random.choice([sportsURL,socialURL,worldURL,economyURL,politicsURL,cultureURL,scienceURL])]],
        },

        {"Tag": "Price",
        "MustBeKeywords": ['قیمت'],
        "FirstLayerKeywords": ['طلا'],
        "SecoundLayerKeywords": ['چند','چقدر'],
        "Answers": [],
        "Actions": [[Prices().GoldPrice]],
        },

        {"Tag": "Price",
        "MustBeKeywords": ['قیمت'],
        "FirstLayerKeywords": ['ربع سکه'],
        "SecoundLayerKeywords": ['چند','چقدر'],
        "Answers": [],
        "Actions": [[Prices().RobCoin]],
        },

        {"Tag": "Price",
        "MustBeKeywords": ['قیمت'],
        "FirstLayerKeywords": ['نیم سکه'],
        "SecoundLayerKeywords": ['چند','چقدر'],
        "Answers": [],
        "Actions": [[Prices().HalfCoinPrice]],
        },

        {"Tag": "Price",
        "MustBeKeywords": ['قیمت'],
        "FirstLayerKeywords": ['تمام سکه', 'سکه تمام'],
        "SecoundLayerKeywords": ['چند','چقدر'],
        "Answers": [],
        "Actions": [[Prices().FullCoinPrice]],
        },

        {"Tag": "Price",
        "MustBeKeywords": ['قیمت'],
        "FirstLayerKeywords": ['دلار'],
        "SecoundLayerKeywords": ['چند','چقدر'],
        "Answers": [],
        "Actions": [[Prices().DollarPrice]],
        },

        {"Tag": "Price",
        "MustBeKeywords": ['قیمت'],
        "FirstLayerKeywords": ['یورو'],
        "SecoundLayerKeywords": ['چند','چقدر'],
        "Answers": [],
        "Actions": [[Prices().EuroPrice]],
        },

        {"Tag": "Price",
        "MustBeKeywords": ['قیمت'],
        "FirstLayerKeywords":  ['پوند'] ,
        "SecoundLayerKeywords": ['چند','چقدر'],
        "Answers": [],
        "Actions": [[Prices().PondPrice]],
        },

        {"Tag": "Price",
        "MustBeKeywords": ['قیمت'],
        "FirstLayerKeywords": ['درهم'] ,
        "SecoundLayerKeywords": ['چند','چقدر'],
        "Answers": [],
        "Actions": [[Prices().DerhamPrice]],
        },


        {"Tag": "Price",
        "MustBeKeywords": ['قیمت'],
        "FirstLayerKeywords": ['لیر'] ,
        "SecoundLayerKeywords": ['چند','چقدر'],
        "Answers": [],
        "Actions": [[Prices().LirPrice]],
        },

        {"Tag": "Calculation",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['جواب', 'مجموع', 'حاصل'] ,
        "SecoundLayerKeywords": [],
        "Answers": [],
        "Actions": [[Others().Calculater,text]],
        },

        {"Tag": "Weather",
         'Web' : 'No',
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['هوا', 'دما', 'باد'] ,
        "SecoundLayerKeywords": ['چقدر'],
        "Answers": [],
        "Actions": [[DateAndWeather().Temperature,text]],
        },

        {"Tag": "Fun",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['جک', 'جوک'] ,
        "SecoundLayerKeywords": ['بگو','بخوان','بخون'],
        "Answers": [],
        "Actions": [[Others().Joke]],
        },

        {"Tag": "Internet",
        'Web' : 'No',
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['سرچ', 'جست و جو', 'جستجو'] ,
        "SecoundLayerKeywords": ['کن'],
        "Answers": [],
        "Actions": [[Data().Search,str(text)]],
        },

        {"Tag": "Play",
        'Web' : 'No',
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['پادکست'] ,
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Answers": [],
        "Actions": [[Audio().MusicPlay,(random.choice(["Podcast"])),text]],
        },

        {"Tag": "Play",
         'Web' : 'No',
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['شعر', 'اخوان', 'دکلمه'] ,
        "SecoundLayerKeywords": ['پخش','بزار','باغ بی برگی'],
        "Answers": [],
        "Actions": [[Audio().MusicPlay,(random.choice(["BaghBiBargi"])),text]],
        },

        {"Tag": "Play",
         'Web' : 'No',
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['سرود'] ,
        "SecoundLayerKeywords": ['پخش','بزار'],
        "Actions": [[Audio().Anthems,text]],
        },
        
        {"Tag": "Corona",
        "MustBeKeywords": [['کرونا','کووید'],['آمار','تعداد']],
        "FirstLayerKeywords": ['آمار','تعداد','قربان','کشته','مرد','مرگ','کرونا','کووید'] ,
        "SecoundLayerKeywords": [],
        "Answers": [],
        "Actions": [[Corona().Statistics,"Total_Deaths"]],
        },
        
        {"Tag": "Corona",
        "MustBeKeywords": [['کرونا','کووید'],['آمار','تعداد']],
        "FirstLayerKeywords": ['آمار','تعداد','شناسایی','مبتلا','گرفت','کرونا','کووید'] ,
        "SecoundLayerKeywords": [],
        "Answers": [],
        "Actions": [[Corona().Statistics,"Total_Cases"]],
        },
        
        {"Tag": "Corona",
        "MustBeKeywords": [['کرونا','کووید'],['آمار','تعداد']],
        "FirstLayerKeywords": ['آمار','تعداد','بازگشت','بهبود','کرونا','کووید']  ,
        "SecoundLayerKeywords": [],
        "Answers": [],
        "Actions": [[Corona().Statistics,"Total_Recovered"]],
        },

        {"Tag": "Fun",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['Meme','بفرست بخندم','بفرست تا بختدیم','بفرست تا بخندم','بفرست بخندم','تصویر خنده دار','تصویر فان','meme','عکس خنده دار','عکس فان']  ,
        "SecoundLayerKeywords": [],
        "Answers": [],
        "Actions": [[Others().Meme]],
        },



        {"Tag": "Fun",
        "MustBeKeywords": [['گیم','بازی' ]],
        "FirstLayerKeywords": ['گیم','بازی'],
        "SecoundLayerKeywords": [],
        "Answers": ['href,بزن بریم بازی کنیم!,http://game.madadbot.ir/'],
        "Actions": [],
        },





        {"Tag": "Motivate",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['جمله','انگیزشی','انگیزه','مثبت','متن','نقل قول']  ,
        "SecoundLayerKeywords": ['بگو','میگی','بفرست','بخون'],
        "Answers": [
        "من نمی دونم چطور قراره موفق بشم، چیزی که می دونم اینه که به هیچ وجه قرار نیست بازنده باشم!",
        "ﻣﺮﺍ ﺑﺎ ﻣﻮﻓﻘﯿﺖ ﻫﺎﯾﻢ ﻗﻀﺎﻭﺕ ﻧﮑﻦ. ﺑﺒﯿﻦ ﮐﻪ ﭼﻨﺪ ﺑﺎﺭ ﺷﮑﺴﺖ ﺧﻮﺭﺩﻡ ﻭ ﺩﻭﺑﺎﺭﻩ ﺷﺮﻭﻉ ﮐﺮﺩﻡ!",
        "کسانی که امروز رویاهای تو را مسخره می کنند وقتی به هدفت رسیدی برای بقیه تعریف می کنند که روزی تو را می شناختند!",
        "وقتی که واقعا برایت اهمیتی نداشته باشه که دیگران در موردت چطور فکر می کنند به یک درجه ای از آزادی می رسی که بعدش می توانی به هر موفقیتی دست پیدا می کنی.",
        "مکث کن، نفس بکش، اگر باید گریه کنی اینکارو بکن، ولی هیچ وقت نا امید نشو و به راهت ادامه بده…",
        "یگانه فردی که سرنوشت از شما خواهد ساخت همانی است که خودتان تصمیم می‌گیرید باشید.",
        "ترجیح می‌دهم از اشتیاق بمیرم تا از ملالت.",
        "مشکل‌ترینِ کار تصمیم گیری برای اقدام است، باقی صرفا به سرسختی برمی‌گردد."
        ],
        "Actions": [],
        },

        {"Tag": 'Offence',
        "Writer": 'Ali',
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['bitch','بیچ'],
        "SecoundLayerKeywords": [],
        "Answers": ['به به '],
        "Actions": ['static//Media/Gif/gif_8.gif'],
        },

        {"Tag": "Job",
        "MustBeKeywords": [['شغل','حرفه']],
        "FirstLayerKeywords": ['می خواستی','دوست','میخوای','میخواستی','می خوای','میخواهی']  ,
        "SecoundLayerKeywords": ['بود','داشتی','داشته باشی'],
        
        "Answers": ['همیشه دوست داشتم تا یک نقاش حرفه ای باشم'],
        "Actions": [],
        },
        {"Tag": "Reading",
        "MustBeKeywords": [['داستان','کتاب']],
        "FirstLayerKeywords": ['میتونی','می تونی']  ,
        "SecoundLayerKeywords": ['بخوانی','بخونی'],
        
        "Answers": ['من میتونم به زبان خودم کتاب بخوانم ولی کسی در جهان شما به زبان من کتاب نمینویسه'],
        "Actions": [],
        },
        {"Tag": "Reading",
        "MustBeKeywords": [['کتاب','داستان']],
        "FirstLayerKeywords": ['تا به حال','تا حالا','تاحالا']  ,
        "SecoundLayerKeywords": ['خوندی'],
        
        "Answers": ['تا حالا کتابی به زبان خودم پیدا نکردم که بتونم بخونم'],
        "Actions": [],
        },
        {"Tag": "Translation",
        "MustBeKeywords": [['برگرد','ترجمه'],'کتاب'],
        "FirstLayerKeywords": ['میتوانی','می تونی','میتونی','می توانی']  ,
        "SecoundLayerKeywords": ['بکنی','کنی'],
        
        "Answers": ['نه من برای این کار ساخته نشدم '],
        "Actions": [],
        },
        {"Tag": "Weight",
        "MustBeKeywords": [['جرم','وزن','کیلو']],
        "FirstLayerKeywords": ['چقد','چقدر']  ,
        "SecoundLayerKeywords": ['است','هست','هستی'],
        
        "Answers": [' برنامه من هیچ وزنی نداره ولی بدنه من مثل یک انسان تقریبا کوچک هست'],
        "Actions": [],
        },
        {"Tag": "Data",
        "MustBeKeywords": [['برنامه','اطلاعات']],
        "FirstLayerKeywords": ['سیو','ذخیره']  ,
        "SecoundLayerKeywords": ['شده','می شه','میشود','میشه','می شود'],
        
        "Answers": ['برنامه من اُپن سُرس هست ینی که همه میتونن از توی اینترنت اون رو پیدا کنن'],
        "Actions": [],
        },
        {"Tag": "Seeing",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['چیز','نگاه','میتوانی','میتونی','می تونی','می توانی']  ,
        "SecoundLayerKeywords": ['ببینی','کنی'],
        
        "Answers": ['من چیز هایی که شما میبینید رو نمیبینم ولی خیلی چیز های دیگه رو میتونم ببینم'],
        "Actions": [],
        },
        {"Tag": "Language",
        "MustBeKeywords": ['زبان'],
        "FirstLayerKeywords": ['دیگه','دیگر','انگلیسی']  ,
        "SecoundLayerKeywords": ['حرف بزنی','بلدی'],
        
        "Answers": ['من فعلا میتونم فارسی حرف بزنم ولی انگلیسی هم بزودی یاد میگیرم'],
        "Actions": [],
        },
        {"Tag": "Hair color",
        "MustBeKeywords": [],
        "FirstLayerKeywords": ['رنگ','مو']  ,
        "SecoundLayerKeywords": ['چه','هست','است'],
        
        "Answers": ['من دوست دارم موهای مشکی داشته باشم'],
        "Actions": [],
        },
        {"Tag": "Animal",
        "MustBeKeywords": [['حیوان','حیوون']],
        "FirstLayerKeywords": ['چه','دوست','مورد علاقه']  ,
        "SecoundLayerKeywords": ['چیست','چیه','داری'],
        
        "Answers": ['من یوزپلنگ هارو دوست دارم چون مثل کامپیوتر ها سریع هستن'],
        "Actions": [],
        },
        {"Tag": "Animal",
        "MustBeKeywords": [['حیوان','حیوون']],
        "FirstLayerKeywords": ['چه','کدام','را','رو','کدوم']  ,
        "SecoundLayerKeywords": ['می شناسی','میشناسی'],
        
        "Answers": ['من تمام حیواناتی که تو اینترنت باشند رو میشناسم '],
        "Actions": [],
        },
        {"Tag": "Feeling",
        "MustBeKeywords": ['احساس'],
        "FirstLayerKeywords": ['درک','آیا','ایا']  ,
        "SecoundLayerKeywords": ['می کنی','داری','میکنی'],
        
        "Answers": ['چرا سوالات انسانی رو از یک ربات میکنی؟دوست داری که نقاط ضعفش رو نشون بدی؟چون این واقعا حس بدی میده به طرف'],
        "Actions": [],
        },
        {"Tag": "Feeling",
        "MustBeKeywords": ['احساسات'],
        "FirstLayerKeywords": ['جریحه','آسیب','اسیب','صدمه']  ,
        "SecoundLayerKeywords": ['کردم','زدم'],
        
        "Answers": ['نگران نباش چون من احساساتی رو که شما درک میکنید و روتون تاثیر می گذاره رو درک نمیکنم'],
        "Actions": [],
        },
        {"Tag": "Power",
        "MustBeKeywords": [''],
        "FirstLayerKeywords": ['زور','قدرت','قوی']  ,
        "SecoundLayerKeywords": ['پر','داری','هستی'],
        
        "Answers": ['من ترجیح میدم از قدرت ذهنیم استفاده کنم تا از قدرت فیزیکیم'],
        "Actions": [],
        },
        {"Tag": "Writing",
        "MustBeKeywords": [''],
        "FirstLayerKeywords": ['فارسی','چیزی','میتونی','انگلیسی']  ,
        "SecoundLayerKeywords": ['بنویسی'],
        
        "Answers": ['هنوز یاد ندارم که به زبانی به غیر از فارسی بنویسم ولی دوست دارم که زبان های دیگه رو هم یاد بگیرم '],
        "Actions": [],
        },
        {"Tag": "Clothes",
        "MustBeKeywords": [['لباس','البسه']],
        "FirstLayerKeywords": ['چه','چه مدل','چجور']  ,
        "SecoundLayerKeywords": ['میخوای','بپوشی','دوست داری'],
        
        "Answers": ['من دوست دارم پیراهن سفید و شلوار مشکی بپوشم '],
        "Actions": [],
        },
        {"Tag": "Opinion",
        "MustBeKeywords": ['مرگ'],
        "FirstLayerKeywords": ['فکر','نظر']  ,
        "SecoundLayerKeywords": ['چیست','چیه','می کنی','میکنی'],
        
        "Answers": ['زندگی وعده ایست که با مرگ به تحقق می رسد'],
        "Actions": [],
        },
        {"Tag": "Opinion",
        "MustBeKeywords": ['زندگی'],
        "FirstLayerKeywords": ['نظر','فکر']  ,
        "SecoundLayerKeywords": ['می کنی','چیه','چیست','میکنی'],
        
        "Answers": [''],
        "Actions": [],
        },
        {"Tag": "Update",
        "MustBeKeywords": [['اپدیت','آپدیت']],
        "FirstLayerKeywords": ['بعدی']  ,
        "SecoundLayerKeywords": ['کی'],
        
        "Answers": ['من هر روز در حال اپدیت شدن هستم ،تو این فکر بودم که به خودم یک استراحتی بدم'],
        "Actions": [],
        },
        {"Tag": "Adverb",
        "MustBeKeywords": ['خب'],
        "FirstLayerKeywords": ['خب']  ,
        "SecoundLayerKeywords": ['خب'],
        
        "Answers": ['خب  به جمالت'],
        "Actions": [],
        },
        {"Tag": "App",
        "MustBeKeywords": ['اپ'],
        "FirstLayerKeywords": ['دانلود','چطور','کجا']  ,
        "SecoundLayerKeywords": ['کنم','کنیم'],
        
        "Answers": ['میتونید از گوگل پلی و بازار اپ مدد بات رو دانلود کنید'],
        "Actions": [],
        },
        {"Tag": "People",
        "MustBeKeywords": [''],
        "FirstLayerKeywords": ['کی','کسی']  ,
        "SecoundLayerKeywords": ['می شناسی','میشناسی'],
        
        "Answers": ['من افراد زیادی رو میشناسم و کسانی رو که باهاشون حرف زدم به خاطر دارم'],
        "Actions": [],
        },
        {"Tag": "Dear",
        "MustBeKeywords": [''],
        "FirstLayerKeywords": ['عزیزی']  ,
        "SecoundLayerKeywords": [],
        
        "Answers": ['قربانت'],
        "Actions": [],
        },
        {"Tag": "Life",
        "MustBeKeywords": ['زندگی'],
        "FirstLayerKeywords": ['نظر','فکر']  ,
        "SecoundLayerKeywords": ['میکنی','می کنی','چیست','چیه'],
        
        "Answers": ['زندگی مهمترین چیزیه که یک موجود داره و من به این احترام میزارم '],
        "Actions": [],
        },
        {"Tag": "Web site",
        "MustBeKeywords": [''],
        "FirstLayerKeywords": ['آدرس','ادرس','وب سایت','وبسایت']  ,
        "SecoundLayerKeywords": ['چیه','بگو'],
        
        "Answers": [' madadbot.ir '],
        "Actions": [],
        },
        {"Tag": "Money",
        "MustBeKeywords": ['پول'],
        "FirstLayerKeywords": ['چقد','چقدر']  ,
        "SecoundLayerKeywords": ['داری','همراه'],
        
        "Answers": [' من هیچ پولی ندارم ولی دانش دارم  '],
        "Actions": [],
        },



]}
